<?php

declare(strict_types=1);

namespace App\Models;

use CodeIgniter\Model;

/**
 * ProductModel
 *
 * Handles validation, relationships, and soft-delete for the products table.
 * Member 3 — relies on this being generated by Member 2, but included here
 * as a reference / fallback if Member 2's version is not yet merged.
 */
class ProductModel extends Model
{
    protected $table            = 'products';
    protected $primaryKey       = 'id';
    protected $useAutoIncrement = true;
    protected $returnType       = 'array';
    protected $useSoftDeletes   = false;
    protected $useTimestamps    = true;
    protected $createdField     = 'created_at';
    protected $updatedField     = 'updated_at';

    protected $allowedFields = [
        'category_id',
        'name',
        'description',
        'brand',
        'base_price',
        'image_path',
        'is_active',
    ];

    protected $validationRules = [
        'name'        => 'required|max_length[255]',
        'category_id' => 'required|integer',
        'brand'       => 'required|max_length[120]',
        'base_price'  => 'required|decimal|greater_than[0]',
        'description' => 'permit_empty|max_length[1000]',
    ];

    protected $validationMessages = [
        'name'       => ['required' => 'Product name is required.'],
        'base_price' => ['greater_than' => 'Price must be greater than zero.'],
    ];

    protected $skipValidation = false;
}